### ISSUE TITLE
Use of tiny-keccak 

### ISSUE THREAD

**Issue by dirvine** [isislovecruft/ed25519-dalek#8]
Not an issue really, so happy you just read and close this :-) 

I wonder if this would help speed as well ? It's a rust version of keccak and seems very fast. I tested this as almost 3 times faster than libsodium sha2 it may be worth a look. https://github.com/debris/tiny-keccak

**Comment by burdges** [comment]
It took folks a while to convince him to remove numerous usages of unsafe in https://github.com/debris/tiny-keccak/pull/8 and https://github.com/debris/tiny-keccak/pull/11 but a couple remain, removing them does not look like a priority, and I've now forgotten if/how endianness impacts them.  I think tiny-keccak was originally meant for some crypto-currency application.  If so, they have little reason to care about safety, endianness, etc. 

According to https://github.com/debris/tiny-keccak/pull/14 the RustCrypto SHA3 copied the good ideas from tiny-keccak anyways, and offers similar performance with a more widespread API.

**Comment by dirvine** [comment]
Ah cheers, sha3 would make this non complaint anyway if tested again nist vectors etc. So crazy idea I will close this issue.
